import os from 'node:os';
import path from 'node:path';

import type { TmuxSocketMode } from './types.js';

export interface NativeInstallOptions {
  prefix: string;
  dataDir: string;
  host: string;
  port: number;
  baseUrl: string;
  allowedRoots: string[];
  backendHost: string;
  backendPort: number;
  backendPublicUrl: string;
  backendName: string;
  backendAuthToken: string;
  tmuxSocketMode: TmuxSocketMode;
  tmuxSocketName: string;
  sessionPrefix: string;
  ohMyTmuxConfigPath: string;
}

export function defaultNativePrefix(): string {
  return path.join(os.homedir(), '.local', 'share', 'tmux-web-manager');
}

export function defaultNativeDataDir(): string {
  return path.join(os.homedir(), '.local', 'state', 'tmux-web-manager');
}

function quoteShellValue(value: string): string {
  return `'${value.replace(/'/g, `'"'"'`)}'`;
}

export function buildEnvFile(options: NativeInstallOptions): string {
  const lines = [
    '# generated by tmux-web-manager native installer',
    `HOST=${quoteShellValue(options.host)}`,
    `PORT=${quoteShellValue(String(options.port))}`,
    `BASE_URL=${quoteShellValue(options.baseUrl)}`,
    `DATA_DIR=${quoteShellValue(options.dataDir)}`,
    `ALLOWED_PROJECT_ROOTS=${quoteShellValue(options.allowedRoots.join(','))}`,
    `BACKEND_HOST=${quoteShellValue(options.backendHost)}`,
    `BACKEND_PORT=${quoteShellValue(String(options.backendPort))}`,
    `BACKEND_PUBLIC_URL=${quoteShellValue(options.backendPublicUrl)}`,
    `BACKEND_NAME=${quoteShellValue(options.backendName)}`,
    `BACKEND_AUTH_TOKEN=${quoteShellValue(options.backendAuthToken)}`,
    `TMUX_SOCKET_MODE=${quoteShellValue(options.tmuxSocketMode)}`,
    `TMUX_SOCKET_NAME=${quoteShellValue(options.tmuxSocketName)}`,
    `SESSION_PREFIX=${quoteShellValue(options.sessionPrefix)}`,
    `OH_MY_TMUX_CONF=${quoteShellValue(options.ohMyTmuxConfigPath)}`,
    '',
  ];
  return lines.join('\n');
}

export function buildRunScript(mode: 'main' | 'sub'): string {
  return [
    '#!/usr/bin/env bash',
    'set -euo pipefail',
    'PREFIX="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"',
    'set -a',
    '. "$PREFIX/etc/tmux-web-manager.env"',
    'set +a',
    'cd "$PREFIX/app"',
    `exec node dist/index.js ${mode}`,
    '',
  ].join('\n');
}
