import fs from 'node:fs';
import path from 'node:path';
import { execFile, spawnSync } from 'node:child_process';
import { promisify } from 'node:util';

import type { TmuxPaneRecord, TmuxSocketMode } from './types.js';

const execFileAsync = promisify(execFile);

export interface ManagedTmuxOptions {
  socketMode: TmuxSocketMode;
  socketName: string;
  configPath: string;
  sessionPrefix: string;
}

export interface DiscoveredTmuxSession {
  tmuxSessionName: string;
  currentPath: string;
  createdAt: string;
  lastActivityAt?: string;
}

type InputPart =
  | { type: 'literal'; value: string }
  | { type: 'key'; value: string };

const SEQUENCE_MAP = new Map<string, string>([
  ['\r', 'Enter'],
  ['\n', 'Enter'],
  ['\t', 'Tab'],
  ['\u007f', 'BSpace'],
  ['\u001b[A', 'Up'],
  ['\u001b[B', 'Down'],
  ['\u001b[C', 'Right'],
  ['\u001b[D', 'Left'],
  ['\u001b[3~', 'Delete'],
  ['\u001b[H', 'Home'],
  ['\u001b[F', 'End'],
  ['\u001b[5~', 'PageUp'],
  ['\u001b[6~', 'PageDown'],
]);

function quoteShellArg(value: string): string {
  return `'${value.replace(/'/g, `'"'"'`)}'`;
}

export function ensureTmuxInstalled(): void {
  const result = spawnSync('tmux', ['-V'], { encoding: 'utf8' });
  if (result.status !== 0) {
    throw new Error('tmux is required but was not found in PATH');
  }
}

export function validateProjectPath(inputPath: string, allowedRoots: string[]): string {
  if (!path.isAbsolute(inputPath)) {
    throw new Error('Project path must be an absolute path');
  }

  const resolvedCandidatePath = path.resolve(inputPath);
  const resolvedRoots = allowedRoots.map((root) => path.resolve(root));
  const isAllowed = resolvedRoots.some((root) => {
    return resolvedCandidatePath === root || resolvedCandidatePath.startsWith(`${root}${path.sep}`);
  });

  if (!isAllowed) {
    throw new Error(`Path is outside allowed roots: ${resolvedCandidatePath}`);
  }

  if (!fs.existsSync(resolvedCandidatePath)) {
    fs.mkdirSync(resolvedCandidatePath, { recursive: true });
  }

  const stats = fs.statSync(resolvedCandidatePath);
  if (!stats.isDirectory()) {
    throw new Error(`Path is not a directory: ${resolvedCandidatePath}`);
  }

  return fs.realpathSync(resolvedCandidatePath);
}

export function buildManagedTmuxConfigContents(sourcePath: string): string {
  const quotedSourcePath = quoteShellArg(sourcePath);
  return [
    '# generated by tmux-web-manager',
    `if-shell "test -f ${quotedSourcePath}" "source-file ${quotedSourcePath}"`,
    'set -g mouse on',
    'set -g history-limit 100000',
    'set -g focus-events on',
    'set -g default-terminal "screen-256color"',
    'set -sg escape-time 0',
    'set -g allow-rename off',
    '',
  ].join('\n');
}

export function buildManagedTmuxConfig(configDir: string, sourcePath: string): string {
  fs.mkdirSync(configDir, { recursive: true });
  const configPath = path.join(configDir, 'managed.tmux.conf');
  fs.writeFileSync(configPath, buildManagedTmuxConfigContents(sourcePath));
  return configPath;
}

async function tmux(args: string[], options: ManagedTmuxOptions): Promise<string> {
  const tmuxArgs =
    options.socketMode === 'dedicated'
      ? ['-L', options.socketName, '-f', options.configPath, ...args]
      : args;
  const { stdout } = await execFileAsync(
    'tmux',
    tmuxArgs,
    { encoding: 'utf8' },
  );
  return stdout;
}

export function isNoServerRunningError(error: unknown): boolean {
  const message = error instanceof Error ? error.message : String(error);
  return /no server running/i.test(message) || /error connecting to .*no such file or directory/i.test(message);
}

function sanitizeSessionName(value: string): string {
  return value.replace(/[^a-zA-Z0-9_-]/g, '-');
}

export function sanitizeTmuxSessionName(value: string): string {
  return sanitizeSessionName(value.trim());
}

export function buildManagedSessionName(
  prefix: string,
  sessionId: string,
  requestedName?: string,
): string {
  const raw = requestedName?.trim() ? requestedName.trim() : `${prefix}-${sessionId.slice(0, 8)}`;
  return sanitizeSessionName(raw);
}

export async function createTmuxSession(
  sessionId: string,
  requestedPath: string,
  options: ManagedTmuxOptions,
  requestedName?: string,
): Promise<{ tmuxSessionName: string; currentPath: string }> {
  const tmuxSessionName = buildManagedSessionName(options.sessionPrefix, sessionId, requestedName);
  await tmux(['new-session', '-d', '-s', tmuxSessionName, '-c', requestedPath], options);
  const currentPath = await getPaneWorkingDirectory(tmuxSessionName, options);
  return { tmuxSessionName, currentPath };
}

export async function renameTmuxSession(
  previousSessionName: string,
  nextSessionName: string,
  options: ManagedTmuxOptions,
): Promise<string> {
  const sanitizedSessionName = sanitizeTmuxSessionName(nextSessionName);
  if (!sanitizedSessionName) {
    throw new Error('sessionName is required');
  }
  if (sanitizedSessionName === previousSessionName) {
    return sanitizedSessionName;
  }
  await tmux(['rename-session', '-t', previousSessionName, sanitizedSessionName], options);
  return sanitizedSessionName;
}

export async function sessionExists(tmuxSessionName: string, options: ManagedTmuxOptions): Promise<boolean> {
  try {
    await tmux(['has-session', '-t', tmuxSessionName], options);
    return true;
  } catch {
    return false;
  }
}

export async function stopTmuxSession(tmuxSessionName: string, options: ManagedTmuxOptions): Promise<void> {
  await tmux(['kill-session', '-t', tmuxSessionName], options);
}

async function getPrimaryPaneTarget(
  tmuxSessionName: string,
  options: ManagedTmuxOptions,
): Promise<string> {
  const stdout = await tmux(['list-panes', '-t', tmuxSessionName, '-F', '#{pane_id}'], options);
  const paneId = stdout
    .split('\n')
    .map((line) => line.trim())
    .find(Boolean);
  if (!paneId) {
    throw new Error(`No pane found for tmux session: ${tmuxSessionName}`);
  }
  return paneId;
}

export async function paneExists(paneId: string, options: ManagedTmuxOptions): Promise<boolean> {
  try {
    const stdout = await tmux(['display-message', '-p', '-t', paneId, '#{pane_id}'], options);
    return stdout.trim() === paneId;
  } catch {
    return false;
  }
}

export async function getPaneWorkingDirectory(
  tmuxSessionName: string,
  options: ManagedTmuxOptions,
): Promise<string> {
  const stdout = await tmux(
    ['display-message', '-p', '-t', tmuxSessionName, '#{pane_current_path}'],
    options,
  );
  return stdout.trim();
}

function epochSecondsToIso(value: string | undefined, fallback?: string): string | undefined {
  const parsed = Number.parseInt(value ?? '', 10);
  if (Number.isFinite(parsed) && parsed > 0) {
    return new Date(parsed * 1000).toISOString();
  }
  return fallback;
}

export async function getSessionActivityAt(
  tmuxSessionName: string,
  options: ManagedTmuxOptions,
): Promise<string | undefined> {
  const stdout = await tmux(
    ['display-message', '-p', '-t', tmuxSessionName, '#{session_activity}'],
    options,
  );
  return epochSecondsToIso(stdout.trim());
}

export async function listTmuxSessions(
  options: ManagedTmuxOptions,
): Promise<DiscoveredTmuxSession[]> {
  let stdout = '';
  try {
    stdout = await tmux(
      ['list-sessions', '-F', '#{session_name}\t#{session_created}\t#{session_activity}'],
      options,
    );
  } catch (error) {
    if (isNoServerRunningError(error)) {
      return [];
    }
    throw error;
  }

  const sessions: DiscoveredTmuxSession[] = [];
  for (const line of stdout.split('\n').map((entry) => entry.trim()).filter(Boolean)) {
    const [tmuxSessionName, createdEpochRaw, activityEpochRaw] = line.split('\t');
    if (!tmuxSessionName) {
      continue;
    }
    try {
      const currentPath = await getPaneWorkingDirectory(tmuxSessionName, options);
      const createdAt = epochSecondsToIso(createdEpochRaw, new Date().toISOString())!;
      sessions.push({
        tmuxSessionName,
        currentPath,
        createdAt,
        lastActivityAt: epochSecondsToIso(activityEpochRaw, createdAt),
      });
    } catch {
      // session may disappear between list and pane lookup
    }
  }
  return sessions;
}

export async function listTmuxPanes(options: ManagedTmuxOptions): Promise<TmuxPaneRecord[]> {
  let stdout = '';
  try {
    stdout = await tmux(
      [
        'list-panes',
        '-a',
        '-F',
        '#{pane_id}\t#{session_name}\t#{window_index}\t#{pane_index}\t#{pane_current_path}\t#{pane_current_command}\t#{pane_title}\t#{@name}\t#{pane_activity}',
      ],
      options,
    );
  } catch (error) {
    if (isNoServerRunningError(error)) {
      return [];
    }
    throw error;
  }

  return stdout
    .split('\n')
    .map((entry) => entry.trim())
    .filter(Boolean)
    .map((line) => {
      const [
        paneId,
        sessionName,
        windowIndexRaw,
        paneIndexRaw,
        currentPath,
        currentCommand,
        title,
        label,
        activityEpochRaw,
      ] = line.split('\t');
      return {
        paneId: paneId || '',
        sessionName: sessionName || '',
        windowIndex: Number.parseInt(windowIndexRaw || '0', 10),
        paneIndex: Number.parseInt(paneIndexRaw || '0', 10),
        currentPath: currentPath || '',
        currentCommand: currentCommand || '',
        title: title || '',
        label: label || '',
        lastActivityAt: epochSecondsToIso(activityEpochRaw),
      };
    })
    .filter((pane) => Boolean(pane.paneId && pane.sessionName));
}

export function splitInput(data: string): InputPart[] {
  const parts: InputPart[] = [];
  let literal = '';
  let index = 0;
  const knownSequences = [...SEQUENCE_MAP.keys()].sort((a, b) => b.length - a.length);

  function flushLiteral() {
    if (literal) {
      parts.push({ type: 'literal', value: literal });
      literal = '';
    }
  }

  while (index < data.length) {
    const sequence = knownSequences.find((candidate) => data.startsWith(candidate, index));
    if (sequence) {
      flushLiteral();
      parts.push({ type: 'key', value: SEQUENCE_MAP.get(sequence)! });
      index += sequence.length;
      continue;
    }

    const char = data[index]!;
    const code = char.charCodeAt(0);
    if (code >= 1 && code <= 26) {
      flushLiteral();
      parts.push({ type: 'key', value: `C-${String.fromCharCode(code + 96)}` });
      index += 1;
      continue;
    }

    literal += char;
    index += 1;
  }

  flushLiteral();
  return parts;
}

export async function sendInput(
  tmuxSessionName: string,
  data: string,
  options: ManagedTmuxOptions,
): Promise<void> {
  const paneTarget = await getPrimaryPaneTarget(tmuxSessionName, options);
  await sendInputToPane(paneTarget, data, options);
}

export async function sendInputToPane(
  paneTarget: string,
  data: string,
  options: ManagedTmuxOptions,
): Promise<void> {
  for (const part of splitInput(data)) {
    if (part.type === 'literal') {
      await tmux(['send-keys', '-t', paneTarget, '-l', '--', part.value], options);
    } else {
      await tmux(['send-keys', '-t', paneTarget, part.value], options);
    }
  }
}

export async function sendKeys(
  tmuxSessionName: string,
  keys: string[],
  options: ManagedTmuxOptions,
): Promise<void> {
  const paneTarget = await getPrimaryPaneTarget(tmuxSessionName, options);
  await sendKeysToPane(paneTarget, keys, options);
}

export async function sendKeysToPane(
  paneTarget: string,
  keys: string[],
  options: ManagedTmuxOptions,
): Promise<void> {
  for (const key of keys) {
    const normalizedKey = key.trim();
    if (!normalizedKey) {
      continue;
    }
    await tmux(['send-keys', '-t', paneTarget, normalizedKey], options);
  }
}

export async function readPaneOutput(
  tmuxSessionName: string,
  lines: number,
  options: ManagedTmuxOptions,
): Promise<string> {
  const paneTarget = await getPrimaryPaneTarget(tmuxSessionName, options);
  return readPaneOutputById(paneTarget, lines, options);
}

export async function readPaneOutputById(
  paneTarget: string,
  lines: number,
  options: ManagedTmuxOptions,
): Promise<string> {
  const normalizedLines = Math.max(1, Math.min(500, Math.floor(lines)));
  return tmux(
    ['capture-pane', '-t', paneTarget, '-p', '-J', '-S', `-${normalizedLines}`],
    options,
  );
}
